name: flodifff
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.8.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aenum==3.1.15
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.14.1
      - amqp==5.3.1
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrs==23.2.0
      - automaton==3.2.0
      - autopage==0.5.2
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - bcrypt==4.3.0
      - bddl==1.0.1
      - beautifulsoup4==4.12.3
      - cachetools==5.3.3
      - certifi==2024.6.2
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cliff==4.7.0
      - cloudpickle==3.0.0
      - cmd2==2.5.11
      - comm==0.2.2
      - contourpy==1.1.1
      - cryptography==44.0.3
      - cycler==0.12.1
      - debtcollector==3.0.0
      - debugpy==1.8.2
      - decorator==5.1.1
      - diffusers==0.33.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - dogpile-cache==1.3.4
      - efficientnet-pytorch==0.7.1
      - einops==0.8.0
      - eventlet==0.39.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - filelock==3.15.1
      - flatbuffers==24.12.23
      - fonttools==4.53.0
      - freetype-py==2.4.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - future==1.0.0
      - futurist==3.0.0
      - gast==0.4.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.37.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gputil==1.4.0
      - greenlet==3.1.1
      - grpcio==1.68.1
      - gym
      - gym-notices==0.0.8
      - h5py==3.11.0
      - hf-xet==1.1.0
      - huggingface-hub==0.31.1
      - hydra-core==1.3.2
      - idna==3.7
      - igibson==2.2.2
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - iso8601==2.1.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupytext==1.16.2
      - keras==2.13.1
      - keystoneauth1==5.8.1
      - keystonemiddleware==10.7.1
      - kiwisolver==1.4.5
      - kombu==5.5.3
      - libclang==18.1.1
      - lightning==2.3.0
      - lightning-utilities==0.11.2
      - llvmlite==0.41.1
      - lmdb==1.5.1
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - meshcut==0.3.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netaddr==1.3.0
      - netifaces==0.11.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.24.3
      - numpy-quaternion==2023.0.4
      - numpy-stl==3.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.10.0.84
      - openstacksdk==4.0.1
      - opt-einsum==3.4.0
      - os-client-config==2.1.0
      - os-service-types==1.7.0
      - osc-lib==3.2.0
      - oslo-cache==3.8.0
      - oslo-concurrency==6.1.0
      - oslo-config==9.6.0
      - oslo-context==5.6.0
      - oslo-db==16.0.0
      - oslo-i18n==6.4.0
      - oslo-log==6.1.2
      - oslo-messaging==14.9.1
      - oslo-metrics==0.9.0
      - oslo-middleware==6.2.0
      - oslo-policy==4.4.0
      - oslo-reports==3.4.0
      - oslo-serialization==5.5.0
      - oslo-service==3.5.0
      - oslo-upgradecheck==2.4.0
      - oslo-utils==7.3.1
      - oslo-versionedobjects==3.4.0
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.4
      - paste==3.10.1
      - pastedeploy==3.1.0
      - pathtools==0.1.2
      - pbr==6.1.1
      - pecan==1.6.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - positional-encodings==6.0.3
      - prettytable==3.10.0
      - progressbar==2.5
      - prometheus-client==0.21.1
      - promise==2.3
      - prompt-toolkit==3.0.47
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py360convert==0.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybullet-svl==3.1.6.4
      - pycadf==4.0.0
      - pycparser==2.22
      - pydot==4.0.0
      - pyglet==2.1.6
      - pygments==2.18.0
      - pyjwt==2.9.0
      - pyopenssl==25.0.0
      - pyparsing==3.1.2
      - pyperclip==1.9.0
      - pysocks==1.7.1
      - pytest==8.2.2
      - python-barbicanclient==7.0.0
      - python-cinderclient==9.6.0
      - python-dateutil==2.9.0.post0
      - python-glanceclient==4.7.0
      - python-heatclient==3.5.0
      - python-keystoneclient==5.5.0
      - python-neutronclient==11.3.1
      - python-novaclient==18.7.0
      - python-octaviaclient==3.9.0
      - python-openstackclient==7.1.4
      - python-swiftclient==4.7.0
      - python-utils==3.8.2
      - pytorch-lightning==2.3.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.5.15
      - repoze-lru==0.7
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requestsexceptions==1.4.0
      - rfc3986==2.0.0
      - routes==2.5.1
      - rpds-py==0.18.1
      - rsa==4.9
      - safetensors==0.4.5
      - scipy==1.10.1
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - shortuuid==1.0.13
      - simplegeneric==0.8.1
      - six==1.16.0
      - smmap==5.0.1
      - soupsieve==2.5
      - sqlalchemy==2.0.40
      - stack-data==0.6.3
      - statsd==4.0.1
      - stevedore==5.3.0
      - sympy==1.12.1
      - taskflow==5.9.1
      - tenacity==9.0.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - testresources==2.0.2
      - testscenarios==0.5.0
      - testtools==2.7.2
      - tokenizers==0.20.3
      - tomli==2.0.1
      - torch==2.1.0
      - torchmetrics==1.4.0.post0
      - torchvision==0.16.0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.46.3
      - transforms3d==0.4.2
      - trimesh==4.4.1
      - triton==2.1.0
      - typing-extensions==4.13.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - vine==5.1.0
      - vit-pytorch==1.7.0
      - wandb==0.13.0
      - warlock==2.0.1
      - warmup-scheduler==0.3
      - wcwidth==0.2.13
      - webob==1.8.9
      - werkzeug==3.0.6
      - wrapt==1.17.0
      - wsme==0.12.1
      - yacs==0.1.8
      - yappi==1.6.10
      - yarl==1.9.4
      - zipp==3.19.2
prefix: /home/user/anaconda3/envs/igibson
